use std::fs;
use std::path::Path;

pub fn generate_lib(
    known_stubs: &str,
    unknown_stubs: &str,
    bindings: &str,
) -> Result<String, Box<dyn std::error::Error>> {
    let command = std::env::args().collect::<Vec<String>>().join(" ");
    let template_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/templates/lib.tpl.rs");
    let mut content = format!("// generated by {}", command);
    content.push_str("\n");
    content.push_str(&fs::read_to_string(template_path)?);
    content.push_str("\n\n");
    content.push_str(known_stubs);
    content.push_str("\n\n");
    content.push_str(unknown_stubs);
    content.push_str("\n\n");
    content.push_str(bindings);
    Ok(content)
}
